blank_issues_enabled: false
contact_links:
  - name: GitHub Community Forum  <<<<testing testing testing>>>>
    url: https://github.community/
    about: Please ask and answer questions here. <<<<testing testing testing>>>>
  - name: GitHub Security Bug Bounty        <<<<testing testing testing>>>>
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.  <<<<testing testing testing>>>>
<<test>
